### ISSUE TITLE
Please provide

### ISSUE THREAD

**Issue by lchojnowski** [MrUndead1996/ld2410s-esphome#1]
Documentation

**Comment by dafunkydan** [comment]
Did you see the Example Configuration [ld2410s.yml](https://github.com/MrUndead1996/ld2410s-esphome/blob/main/ld2410s.yml) ?
In the example *.yaml all configurations can be seen, and in the manual for the ld2410S are the options explained.

While i generally agree, Documentation is always good - i think this is more a raw and work-in-progress-Project.

**Comment by MrUndead1996** [comment]
[There](https://github.com/MrUndead1996/ld2410s-esphome/blob/main/ld2410s.yml) is an example configuration file as was noticed.
[There](https://esphome.io) you can find documentation for each base component which is part of the ld2410s sensor.
[There](https://esphome.io/components/external_components#external-components) you can find instructions on how to use external components in your project.
